version: "3"

services:
    mongo-database:
        image: mongo:3.2
        volumes:
            - mongo-data:/data/db
        networks:
            - raddit-network

    raddit-app:
        #build: .
        image: raddit
        environment:
            - DATABASE_HOST=mongo-database
        ports:
            - "9292:9292"
        networks:
            - raddit-network
        depends_on:
            - mongo-database

volumes:
    mongo-data: {}

networks:
    raddit-network: